version: '3.8'
services:
  aneback:
    build:
     context: .
     dockerfile: dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING.DATASOURCE.URL=jdbc:oracle:thin:@anemonadb_tp?TNS_ADMIN=/app/Wallet_AnemonaDB
      - SPRING.DATASOURCE.USERNAME=ADMIN
      - SPRING.DATASOURCE.PASSWORD=Anemonadm192000
    restart: always